### ISSUE TITLE
퍼블릭 키 질문

### ISSUE THREAD

**Issue by Heavyrisem** [rmagur1203/self-diagnosis#2]
JSEncrypt 에 setPublicKey로 지정한 키 값은 어디서 가져오신 건가요?
서버랑 쌍을 이루는 키여야 작동되지 않나요?

**Comment by rmagur1203** [comment]
늦게 대답해드려서 죄송합니다
https://hcs.eduro.go.kr/ 페이지의 스크립트를 뜯어본 결과
https://rl6cz18qh.toastcdn.net/eduro/js/app.ae983ba6.js 이 스크립트 내에 미리 PublicKey 를 올려두고 서버에서 암호화된 내용을 받아서 가지고 있는 PrivateKey 를 이용해서 복호화를 하는거 같습니다.
그래서 app.ae986ba6.js 에 있는 PublicKey를 썼습니다.

**Comment by Heavyrisem** [comment]
![image](https://user-images.githubusercontent.com/46806498/92826022-30470600-f40b-11ea-8260-1c9e87f2b432.png)
이 부분이 맞나요?
키값으로 보이는건 저거밖에 없는데 한번 더 변환을 해야 쓸수있는건가요?

**Comment by rmagur1203** [comment]
네 원래는 저 값을 넣어도 작동이 되야 하는데 node-jsencrypt 모듈에서 Hex 로 값을 주면 오류가 떠서 Base64 로 변환해서 사용했습니다.

**Comment by Heavyrisem** [comment]
궁금했었는데 답변 감사합니다!
